version: '3'

services:

  php:
    build: ./docker/php
    container_name: package_laravel-php
    volumes:
      - .:/var/www
    networks:
      - app-backend

  pgsql:
    image: postgres
    container_name: app-pgsql
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - app-backend

volumes:
  pgsql-data:
    driver: local

networks:
  app-backend:
    driver: bridge
