version: '3'

services:

  php:
    build: ./docker/php
    container_name: package_laravel-php
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST:-192.168.220.1} remote_enable=1 remote_port=9001"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - .:/var/www
